### PR TITLE
Upgrade BabelNet to 4.0.1

### PR DESCRIPTION
**Pull request by frankier**
This is an attempt to update this for a newer version of BabelNet. It seems to work for some routes, but maybe not for others. Leaving it here in case it helps anyone.

### CODE REVIEW

**Comment by minhlab** [comment]
Thanks for your time! May I ask if it works for both earlier and newer versions?

**Comment by frankier** [comment]
I don't think so. My experience with the compatibility is: first I tried to use the 2.5.1 API with the newer dump, but it didn't work. The data format has changed. Then I tried to use this code as is with the 4.0.1 API, but it needed these changes. I couldn't use this code as is because I only have access to download the 4.0.1 data.

**Comment by frankier** [comment]
It's a bit of an annoying one from a compatibility perspective because I understand it might be nice to have replicability for experiments you performed with the older version. I don't think it's feasible to support multiple versions however.

**Comment by minhlab** [comment]
OK, I'll make some tags and update the README to give version-specific instructions. Thanks again!

**Pull request merged**
